# 读取项目根目录 .config，将 CONFIG_XXX 转为 KCONFIG_XXX 变量供构建脚本使用
function(read_kconfig)
  set(_f "${CMAKE_CURRENT_SOURCE_DIR}/.config")
  if(NOT EXISTS "${_f}")
    message(WARNING "未找到 .config，请先运行: cmake --build build --target menuconfig")
    return()
  endif()
  file(STRINGS "${_f}" _lines REGEX "^CONFIG_")
  foreach(_line IN LISTS _lines)
    if(_line MATCHES "^CONFIG_([A-Za-z0-9_]+)=y$")
      set(KCONFIG_${CMAKE_MATCH_1} ON PARENT_SCOPE)
    elseif(_line MATCHES "^CONFIG_([A-Za-z0-9_]+)=n$")
      set(KCONFIG_${CMAKE_MATCH_1} OFF PARENT_SCOPE)
    elseif(_line MATCHES "^CONFIG_([A-Za-z0-9_]+)=\"(.*)\"$")
      set(KCONFIG_${CMAKE_MATCH_1} "${CMAKE_MATCH_2}" PARENT_SCOPE)
    elseif(_line MATCHES "^CONFIG_([A-Za-z0-9_]+)=(.*)$")
      set(KCONFIG_${CMAKE_MATCH_1} "${CMAKE_MATCH_2}" PARENT_SCOPE)
    endif()
  endforeach()
endfunction()
